//! Conformance tests for the `hef-core-invariants` capability.

mod batched_journal_submissions_confined_behind_the_synchronous_interface;
mod conditional_manifest_publication_filter_exactness_incremental_views_and_rebuildable_caches;
mod crash_recovery_and_hardware_are_correctness_neutral;
mod hej_frame_sizing_and_acknowledgement_hot_path;
mod payload_pushdown_internal_columns_and_refusing_features;
mod probed_journal_device_health_watch_is_correctness_neutral;
mod probed_journal_storage_capabilities_with_a_portable_fallback;
mod source_of_truth_and_visibility_ordering;
mod storage_core_code_runs_unmodified_under_deterministic_simulation;
mod uncached_journal_replay_reads_avoid_double_buffering_the_page_cache;
