//! Conformance tests for the `hef-deletes-and-corrections` capability.

mod corrections_and_deletes_invalidate_model_derived_columns;
mod corrections_as_superseding_events;
mod deletes_via_immutable_deletion_vectors;
mod erasure_as_severance_and_de_identification_per_jurisdiction;
mod late_events_visible_by_sequence_order;
mod per_subject_erasure_via_crypto_shredding;
